---
# tasks file for post-install
#
- name: copy the files
  copy:
    src: "{{mydir}}"
    dest: /tmp/file1.txt 
- name: install NTP server on centOS
  yum:
    name: chrony
    state: present
  when: ansible_distribution == "CentOS" 

- name: install NTP server on Ubuntu
  apt:
    name: ntp
    state: present
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Start NTP server in centos
  service:
    name: chronyd
    state: started
  when: ansible_distribution == "CentOS"

- name: Start NTP server in ubuntu
  service:
    name: ntp
    state: started
  when: ansible_distribution == "Ubuntu"

- name: adding banner to the servers
  copy:
    content: '# This server is managed by ansible, No manual changes'
    dest: /etc/motd
      
- name: Deploy the ntpconf files in centos
  template:
    src: ntpconfig_centos.j2
    dest: /etc/chrony.conf
    backup: yes
  when: ansible_distribution == "CentOS"
  notify:
    - restart NTP server in centos


- name: Deploy the ntpconf files in ubuntu
  template:
    src: ntpconfig_ubuntu.j2
    dest: /etc/ntp.conf
    backup: yes
  when: ansible_distribution == "Ubuntu"
  notify:
    - restart NTP server in ubuntu
