---
- name: dbserver setup
  hosts: db01
  become: yes
    #vars:
    #dbname: mydb
    #userdb: admin
    #userpass: admin


  tasks:
    - debug:
        msg: "db name {{dbname}}"

    - debug:
        msg: "user name of the db: {{userdb}}"

    - name: install mariadb-server
      ansible.builtin.yum:
        name: mariadb-server
        state: present

    - name: start mariadb-server
      ansible.builtin.service:
        name: mariadb
        state: started
     
    - name: install python3-PyMySQL
      ansible.builtin.yum:
        name: python3-PyMySQL
        state: present


    - name: Add new database with name account
      community.mysql.mysql_db:
        name: "{{dbname}}"
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock
    

    - name: Add mysql user 
      community.mysql.mysql_user:
        name: "{{userdb}}"
        password: "{{userpass}}"
        priv: '*.*:ALL'
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock
